services:
  db:
    image: postgres:16-alpine
    container_name: healthfamily-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: healthfamily
      POSTGRES_USER: healthfamily
      POSTGRES_PASSWORD: healthfamily
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
